name: Test on Main (Push & PR)

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Docker & Compose
        run: |
          docker --version
          docker compose version
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Run Tests 1 times
        run: |
          for i in {1..1}; do
            echo "Test run $i/1"
            npm run test:run
          done

      - name: Merge reports
        run: npm run merge:reports

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: report/merged-report.xml
          retention-days: 7

      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

      - name: Compose down (always)
        if: always()
        run: npm run docker:down
